### ISSUE TITLE
does not compile at all

### ISSUE THREAD

**Issue by vvidov** [mhutshow/dash_pilot#1]
case 1 chrome
 flutter run
Connected devices:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.84
Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.42
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)
Please choose one (or "q" to quit): 2
Launching lib\main.dart on Chrome in debug mode...
lib/widgets/home/3d_car.dart:33:34: Error: Expected an identifier, but got '/'.
Try inserting an identifier before '/'.
              ..scale(1.2, 0.6), /
                                 ^
lib/widgets/home/3d_car.dart:34:18: Error: Expected ')' before this.
            child: Container(
                 ^
lib/widgets/home/3d_car.dart:29:27: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
          child: Transform(
                          ^
/E:/flutter/packages/flutter/lib/src/widgets/basic.dart:1299:9: Context: Found this candidate, but the arguments don't
match.
  const Transform({
        ^^^^^^^^^
Waiting for connection from debug service on Chrome...             22.2s
Failed to compile application.

case 2 windows
 flutter run
Connected devices:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.84
Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.42
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)
Please choose one (or "q" to quit): 1
Launching lib\main.dart on Windows in debug mode...
Nuget.exe not found, trying to download or use cached version.
lib/widgets/home/3d_car.dart(33,34): error G25387D61: Expected an identifier, but got '/'. [D:\dev\flutter_projects\dash_pilot\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/widgets/home/3d_car.dart(34,18): error G67247B7E: Expected ')' before this. [D:\dev\flutter_projects\dash_pilot\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/widgets/home/3d_car.dart(29,27): error GA7C8A1BB: Too many positional arguments: 0 allowed, but 1 found. [D:\dev\flutter_projects\dash_pilot\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\dev\flutter_projects\dash_pilot\build\windows\x64\CMakeFiles\87c13ef29a4b1537385fc4d35c4c95ac\flutter_windows.dll.rule;D:\dev\flutter_projects\dash_pilot\build\windows\x64\CMakeFiles\70e84ef27739c1b96c997e676bba362e\flutter_assemble.rule' exited with code 1. [D:\dev\flutter_projects\dash_pilot\build\windows\x64\flutter\flutter_assemble.vcxproj]
Building Windows application...                                     7.3s
Error: Build process failed.

all steps are excuted
Clone the repository:

git clone https://github.com/mhutshow/dash_pilot.git
Navigate to the project directory:

cd dash_pilot
Install dependencies:

flutter pub get
Run the project:

flutter run

**Comment by mhutshow** [comment]
Did you add map api key on index.html?


also please run flutter upgrade to get the latest flutter version.

**Comment by vvidov** [comment]
> Did you add map api key on index.html?
**how can flutter compiler check map keys?**
> also please run flutter upgrade to get the latest flutter version.
**flutter --version**
**Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git**
Framework • revision 5874a72aa4 (8 days ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2

I think it is up to date

**Comment by mhutshow** [comment]
The error is indicating there is a unexpected character lib>widgets>home>3d car>. line 34.

Please remove the /  on that line.
![image](https://github.com/user-attachments/assets/b7cf2b30-8f90-4110-b09a-d9ad00d964f7)

Or, you can just run "git pull". The  issue will be resolved. 

Also add   <script src="https://maps.googleapis.com/maps/api/js?key=APIKEY" defer></script> API key in index.html. to avoid map issue.
